const TEAM_NAMES = {
  "ARZ": "Arizona Diamondbacks",
  "ATL": "Atlanta Braves",
  "BAL": "Baltimore Orioles",
  "BOS": "Boston Red Sox",
  "CHC": "Chicago Cubs",
  "CHW": "Chicago White Sox",
  "CIN": "Cincinnati Reds",
  "CLE": "Cleveland Guardians",
  "COL": "Colorado Rockies",
  "DET": "Detroit Tigers",
  "HOU": "Houston Astros",
  "KCR": "Kansas City Royals",
  "LAA": "Los Angeles Angels",
  "LAD": "Los Angeles Dodgers",
  "MIA": "Miami Marlins",
  "MIL": "Milwaukee Brewers",
  "MIN": "Minnesota Twins",
  "NYM": "New York Mets",
  "NYY": "New York Yankees",
  "PHI": "Philadelphia Phillies",
  "PIT": "Pittsburgh Pirates",
  "SDP": "San Diego Padres",
  "SFG": "San Francisco Giants",
  "SEA": "Seattle Mariners",
  "STL": "St. Louis Cardinals",
  "TBR": "Tampa Bay Rays",
  "TEX": "Texas Rangers",
  "TOR": "Toronto Blue Jays",
  "WSH": "Washington Nationals",
  "ATH": "Athletics"